name: Build Multiplatform project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linux-build:
    name: Build android and desktop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache KMP tooling
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-kmp-${{ hashFiles('**/*.gradle.kts', '**/*.toml') }}

      - name: Build android and desktop application
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: :composeApp:assembleRelease :composeApp:packageDistributionForCurrentOS -Dsplit_targets

  macos-build:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache KMP tooling
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-kmp-${{ hashFiles('**/*.gradle.kts', '**/*.toml') }}

      - name: Build iOS application
        run: xcodebuild -project iosApp/iosApp.xcodeproj -configuration Debug -scheme iosApp -sdk iphoneos -destination name='iPhone 14 Pro' build
