name: Build Multiplatform project

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  android-build:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache KMP tooling
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-android-${{ hashFiles('**/*.gradle.kts', '**/*.toml') }}

      - name: Build android application
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: :composeApp:assembleRelease -Dsplit_targets

  desktop-build:
    name: Build Desktop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache KMP tooling
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-desktop-${{ hashFiles('**/*.gradle.kts', '**/*.toml') }}

      - name: Build desktop application
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: :composeApp:packageDistributionForCurrentOS -Dsplit_targets

  ios-build:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache KMP tooling
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-ios-${{ hashFiles('**/*.gradle.kts', '**/*.toml') }}

      - name: Build iOS application
        run: xcodebuild -project iosApp/iosApp.xcodeproj -configuration Debug -scheme iosApp -sdk iphoneos -destination name='iPhone 14 Pro' build
