name: Build Multiplatform project

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  linux-build:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build -Dsplit_targets

  macos-build:
    name: Build on macos
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build -Dsplit_targets

      - name: Build iOS application
        run: xcodebuild -project iosApp/iosApp.xcodeproj -scheme iosApp -sdk iphonesimulator -arch x86_64 build
